// <auto-generated>
// 🚨 构建时从 engine.py 的 LANGS 生成，**勿手改**。
//    生成器：voice_ime/pc/gen_shared.py
// 🚨 这里原来是 Backend.swift 里手抄的一份，停在 9 门而 LANGS 已 31 门。
//    接进生成链之后，改 LANGS 三端一起动，不用再靠谁记得。
// </auto-generated>
import Foundation

enum GenLangs {
    /// 目标语言 -> (中文名, 给模型的描述)。顺序跟 engine.LANGS 一致。
    static let langs: [(code: String, label: String, name: String)] = [
        ("en", "English", "English"),
        ("zh", "\u{4E2D}\u{6587}", "Simplified Chinese (\u{7B80}\u{4F53}\u{4E2D}\u{6587}). Use Mainland China wording and simplified characters throughout, never traditional."),
        ("zht", "\u{7E41}\u{9AD4}\u{4E2D}\u{6587}", "Traditional Chinese (\u{7E41}\u{9AD4}\u{4E2D}\u{6587}), TAIWAN conventions. THREE hard requirements: (1) TRADITIONAL characters throughout (\u{6703}/\u{5831}/\u{807D}/\u{958B}/\u{5BE6}), never simplified; (2) TAIWAN vocabulary \u{2014} use \u{8EDF}\u{9AD4}/\u{7DB2}\u{8DEF}/\u{5F71}\u{7247}/\u{8CC7}\u{8A0A}/\u{8A2D}\u{5B9A}/\u{6A94}\u{6848}/\u{7A0B}\u{5F0F}/\u{6ED1}\u{9F20}/\u{5217}\u{5370}, NOT \u{8F6F}\u{4EF6}/\u{7F51}\u{7EDC}/\u{89C6}\u{9891}/\u{4FE1}\u{606F}/\u{8BBE}\u{7F6E}/\u{6587}\u{4EF6}/\u{7A0B}\u{5E8F}/\u{9F20}\u{6807}/\u{6253}\u{5370}; (3) Taiwan punctuation: full-width \u{300C}\u{300D} for quotes, not \u{201C}\u{201D}. This is Mandarin in traditional script \u{2014} do NOT write Cantonese."),
        ("ja", "\u{65E5}\u{672C}\u{8A9E}", "Japanese"),
        ("fr", "Fran\u{E7}ais", "French"),
        ("de", "Deutsch", "German"),
        ("es", "Espa\u{F1}ol", "Spanish"),
        ("ko", "\u{D55C}\u{AD6D}\u{C5B4}", "Korean"),
        ("yue", "\u{7CB5}\u{8A9E}", "written Cantonese (\u{7CA4}\u{8BED}\u{4E66}\u{9762}\u{8BED}). THREE hard requirements: (1) TRADITIONAL characters throughout (\u{6703}/\u{5831}/\u{807D}/\u{5605}), never simplified; (2) Cantonese VOCABULARY, not Mandarin words in traditional skin \u{2014} use \u{807D}\u{65E5}/\u{5C0B}\u{65E5}/\u{4E0B}\u{661F}\u{671F}\u{4E00}/\u{800C}\u{5BB6}/\u{4F9D}\u{5BB6}/\u{7540}/\u{540C}\u{2026}\u{8B1B}/\u{5514}\u{8A72}/\u{9EDE}\u{89E3}/\u{908A}\u{500B}/\u{5F97}\u{9592}/\u{540C}\u{57CB}, NOT \u{660E}\u{5929}/\u{6628}\u{5929}/\u{4E0B}\u{5468}\u{4E00}/\u{73B0}\u{5728}/\u{7ED9}/\u{8DDF}\u{2026}\u{8BF4}/\u{8C22}\u{8C22}/\u{4E3A}\u{4EC0}\u{4E48}/\u{54EA}\u{4E2A}; (3) Cantonese grammar words: \u{5605}\u{3001}\u{5514}\u{3001}\u{4FC2}\u{3001}\u{5497}\u{3001}\u{55BA}\u{3001}\u{4F62}\u{3001}\u{5187}\u{3001}\u{7747}\u{3001}\u{5572}\u{3001}\u{5481}\u{3001}\u{4E5C}\u{5622}\u{3001}\u{35CE}\u{3001}\u{561E}. (4) Use these exact characters so text-to-speech reads them correctly: write \u{7FFB}\u{569F} (NOT \u{8FD4}\u{569F}/\u{7FFB}\u{9ECE}/\u{8FD4}\u{9ECE}), \u{569F} not \u{9ECE}, \u{5481} not \u{7518}, \u{5605} not \u{65E2}, \u{5622} not \u{91CE}, \u{5571} not \u{5CA9}, \u{7540} not \u{6BD4}, \u{5572} not D. Example: \u{300C}\u{4EFD}\u{5831}\u{8868}\u{6211}\u{807D}\u{65E5}\u{4E0B}\u{665D}\u{4E09}\u{9EDE}\u{524D}\u{7540}\u{4F60}\u{FF0C}\u{4EF2}\u{8981} cc \u{57CB} Annie\u{3002}\u{300D}"),
        ("ar", "\u{627}\u{644}\u{639}\u{631}\u{628}\u{64A}\u{629}", "Modern Standard Arabic (MSA, fus-ha) \u{2014} the pan-Arab written standard. Do NOT write Egyptian, Levantine, Gulf or Maghrebi dialect: text-to-speech uses an MSA voice and will mangle dialect text."),
        ("he", "\u{5E2}\u{5D1}\u{5E8}\u{5D9}\u{5EA}", "Modern Hebrew as written in Israel today."),
        ("fa", "\u{641}\u{627}\u{631}\u{633}\u{6CC}", "Persian (Farsi) as written in IRAN, Perso-Arabic script. Not Dari (Afghanistan) and not Tajik (Cyrillic)."),
        ("tr", "T\u{FC}rk\u{E7}e", "Turkish as written in Turkey."),
        ("pt", "Portugu\u{EA}s", "EUROPEAN Portuguese as written in Portugal. Use Portugal spelling and vocabulary (comboio, autocarro, telem\u{F3}vel, casa de banho) and the Portuguese use of tu/voc\u{EA}. NOT Brazilian Portuguese."),
        ("pt_br", "Portugu\u{EA}s (Brasil)", "BRAZILIAN Portuguese as written in Brazil. Use Brazilian spelling and vocabulary (trem, \u{F4}nibus, celular, banheiro) and Brazilian pronoun habits (voc\u{EA} as the default second person, gerund-heavy phrasing). NOT European Portuguese."),
        ("it", "Italiano", "Italian as written in Italy."),
        ("nl", "Nederlands", "Dutch as written in the Netherlands."),
        ("pl", "Polski", "Polish as written in Poland."),
        ("sv", "Svenska", "Swedish as written in SWEDEN. Not Danish, not Norwegian."),
        ("no", "Norsk", "Norwegian BOKMAL (the majority written standard) as written in NORWAY. Not Nynorsk, not Danish, not Swedish."),
        ("da", "Dansk", "Danish as written in DENMARK. Not Norwegian, not Swedish."),
        ("el", "\u{395}\u{3BB}\u{3BB}\u{3B7}\u{3BD}\u{3B9}\u{3BA}\u{3AC}", "MODERN Greek as written in Greece today, monotonic orthography. Not Ancient or Katharevousa Greek."),
        ("vi", "Ti\u{1EBF}ng Vi\u{1EC7}t", "Vietnamese as written in Vietnam, with full diacritics."),
        ("id", "Bahasa Indonesia", "INDONESIAN (Bahasa Indonesia) as written in Indonesia. Not Malay (Bahasa Melayu)."),
        ("hi", "\u{939}\u{93F}\u{928}\u{94D}\u{926}\u{940}", "Hindi in DEVANAGARI script as written in India. Not Urdu."),
        ("th", "\u{E44}\u{E17}\u{E22}", "Thai as written in Thailand."),
        ("ru", "\u{420}\u{443}\u{441}\u{441}\u{43A}\u{438}\u{439}", "Russian as written in Russia, Cyrillic script."),
        ("uk", "\u{423}\u{43A}\u{440}\u{430}\u{457}\u{43D}\u{441}\u{44C}\u{43A}\u{430}", "Ukrainian as written in Ukraine, Ukrainian Cyrillic (i, i-dotted, ye, yi). Not Russian."),
        ("cs", "\u{10C}e\u{161}tina", "Czech as written in Czechia."),
        ("hu", "Magyar", "Hungarian as written in Hungary."),
        ("ro", "Rom\u{E2}n\u{103}", "Romanian as written in Romania, with diacritics."),
    ]
}
